language: node_js
node_js:
  - 8

before_deploy:
  - npm run predeploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: example/build
  on:
    branch: master
