/**
 * See: https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/Map-docpage/#Map__events-summary
 */
export default {
  onActionBegin: 'actionbegin',
  onActionBreak: 'actionbreak',
  onActionEnd: 'actionend',
  onActionTick: 'actiontick',
  onActionTickComplete: 'actiontickcomplete',
  onBalloonClose: 'balloonclose',
  onBalloonOpen: 'balloonopen',
  onBoundsChange: 'boundschange',
  onClick: 'click',
  onContextMenu: 'contextmenu',
  onDoubleClick: 'dblclick',
  onDestroy: 'destroy',
  onHintClose: 'hintclose',
  onHintOpen: 'hintopen',
  onMarginChange: 'marginchange',
  onMouseDown: 'mousedown',
  onMouseEnter: 'mouseenter',
  onMouseLeave: 'mouseleave',
  onMouseMove: 'mousemove',
  onMouseUp: 'mouseup',
  onMultiTouchEnd: 'multitouchend',
  onMultiTouchMove: 'multitouchmove',
  onMultiTouchStart: 'multitouchstart',
  onOptionsChange: 'optionschange',
  onSizeChange: 'sizechange',
  onTypeChange: 'typechange',
  onWheel: 'wheel',
};
